parameters:
#    my_app_filmotheque.example.class: MyApp\FilmothequeBundle\Example

services:
#    my_app_filmotheque.example:
#        class: %my_app_filmotheque.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
