security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall pour les pages de connexion, inscription, et récupération de mot de passe
        # Les adresses de ces pages sont login, register et resetting
        # On autorise bien évidemment les anonymes sur ces pages !
        login:
            pattern:   ^/(login$|register|resetting)
            anonymous: true
        
        # Firewall principal pour le reste de notre site
        # ^/ = tout ce qui commence par / = tout notre site
        # On définit notre méthode d'authentification
        # On lit l'authentification au provider définit plus haut
        # On active la possibilité du "Se souvenir de moi" (désactivé par défaut)
        
        # On définit la clé pour le remember_me (%secret% est un parametre de parameters.ini)
        # On autorise les utilisateurs anonymes (non identifiés)
        # On autorise la déconnexion manuelle (désactivé par défaut)
        main:
            pattern: ^/
            form_login:                      
                provider:    fos_userbundle
                remember_me: true
            remember_me:
                key:         %secret%
            anonymous:       true
            logout:          true

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
