BookBundleHomepage:
    pattern:  /hello/{name}
    defaults: { _controller: BookBundle:Default:index }
    
BookBundleAuthor:
    resource: "@BookBundle/Resources/config/routing/author.yml"

BookBundleBook:
    resource: "@BookBundle/Resources/config/routing/book.yml"
