BookBundleHomepage:
    pattern:  /bookbundle/hello/{name}
    defaults: { _controller: BookBundle:Default:index }
    
BookBundAuthor:
    resource: "@BookBundle/Resources/config/routing/author.yml"

BookBundBook:
    resource: "@BookBundle/Resources/config/routing/book.yml"
