BookBundle_homepage:
    pattern:  /bookbundle/hello/{name}
    defaults: { _controller: BookBundle:Default:index }
author:
    pattern:  /author/
    defaults: { _controller: "BookBundle:Author:index" }