author:
    pattern:  /author/
    defaults: { _controller: "BookBundle:Author:index" }

author_show:
    pattern:  /author/{id}/show
    defaults: { _controller: "BookBundle:Author:show" }

author_new:
    pattern:  /author/new
    defaults: { _controller: "BookBundle:Author:new" }

author_create:
    pattern:  /author/create
    defaults: { _controller: "BookBundle:Author:create" }
    requirements: { _method: post }

author_edit:
    pattern:  /author/{id}/edit
    defaults: { _controller: "BookBundle:Author:edit" }

author_update:
    pattern:  /author/{id}/update
    defaults: { _controller: "BookBundle:Author:update" }
    requirements: { _method: post }

author_delete:
    pattern:  /author/{id}/delete
    defaults: { _controller: "BookBundle:Author:delete" }
    requirements: { _method: post }
