book:
    pattern:  /book/
    defaults: { _controller: "BookBundle:Book:index", _local: en }
    requirements:
      _local: fr|en

book_show:
    pattern:  /book/{id}/show
    defaults: { _controller: "BookBundle:Book:show" }

book_new:
    pattern:  /book/new
    defaults: { _controller: "BookBundle:Book:new" }

book_create:
    pattern:  /book/create
    defaults: { _controller: "BookBundle:Book:create" }
    requirements: { _method: post }

book_edit:
    pattern:  /book/{id}/edit
    defaults: { _controller: "BookBundle:Book:edit" }

book_update:
    pattern:  /book/{id}/update
    defaults: { _controller: "BookBundle:Book:update" }
    requirements: { _method: post }

book_delete:
    pattern:  /book/{id}/delete
    defaults: { _controller: "BookBundle:Book:delete" }
    requirements: { _method: post }
